//LOGIN

export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUESTING = 'LOGIN_USER_REQUESTING';


//SIGNUP

export const SIGN_UP_REQUESTING = 'SIGN_UP_REQUESTING';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

